---
- name: Install needed tools
  package:
    name:
      - unzip
    state: present
- name: Install app
  include_tasks: spring.yml

- name: Install as service
  include_tasks: service.yml

- name: Flush handlers before wait
  meta: flush_handlers

- name: Wait until appication is available
  uri:
    url: "{{ springboot_application_url }}/actuator/health"
    return_content: true
    validate_certs: false
    status_code:
      - 200
      - 401
  until: uri_output.status == 200 or uri_output.status == 401
  # Retries for 24 * 5 seconds = 120 seconds = 2 minutes
  retries: 24
  # Every 5 seconds
  delay: 5
  register: uri_output
