name: Release Role to Ansible Galaxy

on:
  # allow to manual run the action
  workflow_dispatch: { }
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Ansible Galaxy Import
        env:
          GALAXY_API_TOKEN: ${{ secrets.ANSIBLE_GALAXY_API_TOKEN }}
        run: |
          ansible-galaxy role import cloudtooling ansible-role-springboot --token ${ANSIBLE_GALAXY_API_TOKEN}
