name: Build
on:
  pull_request:
  merge_group:
  push:
    branches:
      - develop
defaults:
  run:
    working-directory: 'CloudTooling.springboot'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'CloudTooling.springboot'
      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install test dependencies.
        run: pip3 install yamllint
      - name: Lint code.
        run: |
          yamllint .
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: ubuntu2004
            playbook: converge.yml
            experimental: false
          - distro: debian10
            playbook: converge.yml
            experimental: false
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'CloudTooling.springboot'
      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[docker] docker
      - name: Run Molecule tests.
        run: molecule test
        continue-on-error: ${{ matrix.experimental }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_PLAYBOOK: ${{ matrix.playbook }}
